### ISSUE TITLE
Used reliability-scanner plugin - unfortunately there was an ImagePullBackOff error.

### ISSUE THREAD

**Issue by rashed-k** [vmware-tanzu/sonobuoy-plugins#175]
Used reliability-scanner plugin - unfortunately there was an ImagePullBackOff error. 

`Warning  Failed     22s (x2 over 38s)  kubelet            Failed to pull image "projects.registry.vmware.com/cre/reliability-scanner:v0.1.5": rpc error: code = Unknown desc = Error response from daemon: unknown: artifact cre/reliability-scanner:v0.1.5 not found
  Warning  Failed     22s (x2 over 38s)  kubelet            Error: ErrImagePull
  Normal   BackOff    10s (x3 over 36s)  kubelet            Back-off pulling image "projects.registry.vmware.com/cre/reliability-scanner:v0.1.5"
  Warning  Failed     10s (x3 over 36s)  kubelet            Error: ImagePullBackOff`

**Comment by peterjamesgrant** [comment]
Hi Rashed,

An internal cleanup process lifcycled this image. I have built and pushed the image again and set values for appropriate retention.
