### ISSUE TITLE
BUG!!!  image "kube-bench" does not exist 

### ISSUE THREAD

**Issue by zhengbingxian** [vmware-tanzu/sonobuoy-plugins#181]
dockerhub images name: sonobuoy/kube-bench:0.6.10
code and when sonobuoy run, the  image name is : sonobuoy/kube-bench:v0.6.10 [here](https://github.com/vmware-tanzu/sonobuoy-plugins/blob/main/cis-benchmarks/kube-bench-master-plugin.yaml#:~:text=image%3A%20sonobuoy/kube%2Dbench%3Av0.6.10)

## Do you see the difference？There's a v missing.
sonobuoy/kube-bench:0.6.10
sonobuoy/kube-bench:v0.6.10

Don't you check it before , for such a serious bug ???  unbelievable

**Comment by pydctw** [comment]
Hi @zhengbingxian, thanks for reporting the issue. We have some new contributors and probably missed it. Thanks for understanding. v0.6.10 got published.

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/30200479/205715127-5169a863-0e5f-4736-9fa7-504173a05c59.png">

Let me know if we can close the issue.

**Comment by zhengbingxian** [comment]
I suggest  to add a  test to validate the program  at least .
