### ISSUE TITLE
Sonobuoy aqua plugin failed to start

### ISSUE THREAD

**Issue by kuzm1ch** [vmware-tanzu/sonobuoy-plugins#28]
Platform: Openshift 4.4 
Kubernetes server version:  v1.17.1+912792b

``` 
~ wget https://raw.githubusercontent.com/vmware-tanzu/sonobuoy-plugins/master/kube-hunter/kube-hunter-plugin.yaml
 ~ sonobuoy version
Sonobuoy Version: v0.18.3
MinimumKubeVersion: 1.16.0
MaximumKubeVersion: 1.18.99
GitSHA: 3e8a10e5145f21840b308b76487f3e10b9c1261d
API Version check skipped due to missing `--kubeconfig` or other error
➜  ~ sonobuoy run -f kube-hunter-plugin.yaml  --dns-namespace openshift-dns --dns-pod-labels dns.operator.openshift.io/daemonset-dns=default
ERRO[0000] error attempting to run sonobuoy: couldn't decode template: unmarshalerDecoder: Object 'Kind' is missing in '{"sonobuoy-config":{"driver":"Job","plugin-name":"kube-hunter","result-format":"raw"},"spec":{"command":["/bin/sh","-c","python kube-hunter.py --pod --report=json | tee /tmp/results/report.json \u0026\u0026 echo -n /tmp/results/report.json \u003e /tmp/results/done"],"image":"sonobuoy/kube-hunter:v0.2.0","name":"plugin","resources":{},"volumeMounts":[{"mountPath":"/tmp/results","name":"results"}]}}', error found in #10 byte of ...|sults"}]}}|..., bigger context ...|:[{"mountPath":"/tmp/results","name":"results"}]}}|...
```

**Comment by zubron** [comment]
Hi @kuzm1ch! To run a plugin, you need to use the `--plugin` or `-p` flag followed by the file name. In the command above you used `-f` which is used to pass a complete sonobuoy manifest (the output from `sonobuoy gen`).

I've just tried running `sonobuoy run --dns-namespace openshift-dns --dns-pod-labels dns.operator.openshift.io/daemonset-dns=default -p kube-hunter-plugin.yaml` on an OpenShift cluster (using [CodeReady Containers](https://developers.redhat.com/products/codeready-containers/overview)) and it is running successfully.

I'm going to close this issue, but if you have any problems with the instructions above, feel free to reopen!

**Comment by kuzm1ch** [comment]
@zubron https://github.com/vmware-tanzu/sonobuoy-plugins/pull/29 
update related readme with the same fix
