### ISSUE TITLE
who-can plugin throws "server doesnt have resource type" error

### ISSUE THREAD

**Issue by ruheenaansari34** [vmware-tanzu/sonobuoy-plugins#31]
Hi,

Thank you for creating who-can plugin. I am trying to run the plugin in my cluster and I get the below error:
`running who can: running checker: resolving resource: the server doesn't have a resource type "pods/node_netstat_TcpExt_SyncookiesFailed"`

Please advise as I am not sure if this is a limitation of the plugin that it cannot recognize named resources such as `pods/mypodname`. If so, could you help me workaround this problem.

**Comment by vladimirvivien** [comment]
Hi @ruheenaansari34 
Thank you for reaching out. The error is coming from the server and the plugin is reporting it.  So ensure that pod `node_netstat_TcpExt_SyncookiesFailed` in the namespace that you are in. 

Thanks

**Comment by ruheenaansari34** [comment]
I see similar errors for resources that don't exist. (example: `the server doesn't have a resource type "services/prometheus_target_interval_length_seconds_sum"`; `the server doesn't have a resource type "namespaces/node_memory_Active_file_bytes"`).
Can you tell me why is `who-can` trying to GET these resources that are not supposed to be there in the first place.

**Comment by vladimirvivien** [comment]
Hi @ruheenaansari34 the who-can Sonobuoy plugin is a wrapper of the who-can project (https://github.com/aquasecurity/kubectl-who-can).  It is possible that the Sonobuoy plugin is attempting to audit a namespace that does it does not have access to.  You can attemtp to fix this in the following ways

Download the YAML for the who-can plugin
```sh
wget https://raw.githubusercontent.com/vmware-tanzu/sonobuoy-plugins/master/who-can/who-can.yaml
```
Which should look like https://github.com/vmware-tanzu/sonobuoy-plugins/blob/master/who-can/who-can.yaml.

Next, update the YAML's `WHO_CAN_CONFIG` env variable to specify the accessible namespaces that contain objects you want to audit.  Remove the `*` and add specific namespace you want to autdit:

```yaml
...
  env:
  - name: WHO_CAN_CONFIG
    value: |
      namespaces:
        - kube-system
        - "*"
```
Lastly, run the local copy of your plugin:

```sh
sonobuoy run --plugin who-can.yaml
```

For additional detail, see the doc [here](https://github.com/vmware-tanzu/sonobuoy-plugins/tree/master/who-can).

**Comment by zubron** [comment]
Hi @ruheenaansari34. The who-can plugin uses a Kubernetes discovery client to build a list of all the API resources that it should check, and the result of that should not include named resources like "pod/podname". It should include resources (`pods`, `services`) and any subresources for those (`pods/logs`, `services/status`).

The resources that it's trying to query look like prometheus metric names, so it almost seems like those were reported as subresource types by the API server? Although I have no idea why that would happen. I'm guessing that if you run `kubectl get services -A`, `prometheus_target_interval_length_seconds_sum` does not exist in the output. I don't know of a way to easily output the subresources. @vladimirvivien do you know of a way to get that information?

**Comment by ruheenaansari34** [comment]
Thanks for the explanation. I have verified that none of the resources in the cluster where I'm running sonobuoy who-can are named like "pod/podname". I have configured the `WHO_CAN_CONFIG` env var to a single namespace and received yet another error. 
`Error: running who can: running checker: resolving resource: the server doesn't have a resource type "jobs.batch/node_ipvs_incoming_packets"`

**Comment by kvonbredow** [comment]
So after looking into this a little more, @ruheenaansari34 and I have been able to determine that these subresources come from the Custom Metrics API, specifically ones which were created by the [prometheus-adapter](https://github.com/DirectXMan12/k8s-prometheus-adapter).  Also, it appears they all have the kind `MetricsValueList`.  Would it be possible to have this plugin just ignore these resources through the config?

**Comment by johnSchnake** [comment]
I'm sorry that this seems to have gotten dropped. Is this still an issue for you? As @zubron said above, the functionality is really provided by https://github.com/aquasecurity/kubectl-who-can so if there is a request for extended functionality (e.g. skipping certain kinds of resources), that would be the place to make those asks.
