### ISSUE TITLE
Inventory Plugin - support for CSI

### ISSUE THREAD

**Issue by vladimirvivien** [vmware-tanzu/sonobuoy-plugins#32]
As a user of the Inventory plugin, I should be able to retrieve the following information:
* Ability to discover CSI providers
* Storage classes
* Mapping pods to PersitentVolumes

**Comment by johnSchnake** [comment]
I need to take a look at this plugin; are you saying it is manually querying each resource?

I'm not sure what this plugin accomplishes that sonobuoy queries dont. The queries do everything dynamically so you can get 'all the things'.

I've never run this plugin so I guess I'll have to take more time to walk through it. We'd always thought about pulling the queries out of Sonobuoy into a plugin so maybe this 'inventory' would be a good home/branding for it.

**Comment by johnSchnake** [comment]
I need to take a look at this plugin; are you saying it is manually querying each resource?

I'm not sure what this plugin accomplishes that sonobuoy queries dont. The queries do everything dynamically so you can get 'all the things'.

I've never run this plugin so I guess I'll have to take more time to walk through it. We'd always thought about pulling the queries out of Sonobuoy into a plugin so maybe this 'inventory' would be a good home/branding for it.
