### ISSUE TITLE
Inventory Plugin - Ability to retrieve object fields directly

### ISSUE THREAD

**Issue by vladimirvivien** [vmware-tanzu/sonobuoy-plugins#33]
As a user of inventory plugin I should be able to retrieve all object fields or specific fields from a given objects by providing some sort of query or string to select object and field names.

**Comment by johnSchnake** [comment]
Could you describe a bit better what you mean? At a first reading it just sounds like we get _all_ the data and another tool like `jq` can parse out individual fields if they want it.

**Comment by vladimirvivien** [comment]
@johnSchnake this was an old ask and dont remember the details.  Users of hits plugin have not pushed for this and I think this can be closed.
