### ISSUE TITLE
CIS kube-bench not publshed

### ISSUE THREAD

**Issue by ghoff** [vmware-tanzu/sonobuoy-plugins#47]
An update to the CIS plugin using version 0.5.0 of kube-bench was checked on March 3, but there is no sonobuoy/kube-bench:0.5.0 at docker hub.

**Comment by wilsonehusin** [comment]
woops we missed this one -- [it's out now](https://hub.docker.com/layers/sonobuoy/kube-bench/0.5.0/images/sha256-131935e5ab376298b6d5474f3a164164cf2c177439f7ef5061e70547f58c827b), thanks for notifying!
