### ISSUE TITLE
Sonobuoy CIS Benchmark plugin should support CIS Kubernetes V1.20 Benchmark v1.0.0

### ISSUE THREAD

**Issue by eratnch** [vmware-tanzu/sonobuoy-plugins#51]
With the release of [CIS Kubernetes v1.20 benchmark](https://workbench.cisecurity.org/benchmarks/6246), the CIS benchmark plugin should also support the new benchmark.

**Comment by johnSchnake** [comment]
I'll start tackling this today; lots has changed with the plugin and kube-bench in general since I did this last so it may take a bit though. Lots of extra platforms seem to have special logic too and I can't personally test them all, unfortunately.

**Comment by johnSchnake** [comment]
Someone just bumped the version of kube-bench to 0.6.3; it was able to run as is after the bump so I merged it.

You may want to see if this has what you need in it.
